stages:
  - build
  - release
  - deploy
  - verify

variables:
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DEV_TAG: $CI_PIPELINE_ID

build:
  stage: build
  image: docker:dind
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $CI_REGISTRY
    - docker build  -t $IMAGE_TAG:$CI_PIPELINE_ID .
    - docker push $IMAGE_TAG:$CI_PIPELINE_ID

deploy-k8s:
  stage: deploy
  image: $IMAGE_TAG:$CI_PIPELINE_ID
  script:
    - sed -i -e 's|<IMAGE_TAG>|'$CI_REGISTRY'/'$CI_PROJECT_NAMESPACE'/'$CI_PROJECT_NAME':'$CI_PIPELINE_ID'|g' deployment.yaml
    - sed -i -e 's|<REPOSITORY_NAME>|'$CI_PROJECT_NAME'|g' deployment.yaml
    - sed -i -e 's|<DOMAIN>|'$DOMAIN'|g' deployment.yaml
    - cat deployment.yaml
    - echo "$kube_config" | base64 -d > .config
    - kubectl --kubeconfig .config apply -f deployment.yaml

verify-k8s-deployment:
  stage: verify
  script:
    - echo "$kube_config" | base64 -d > .config
    - kubectl --kubeconfig .config rollout status deployment/$CI_PROJECT_NAME
