image: node:alpine

stages:
  - code_quality

eslint:
  stage: code_quality
  before_script:
    - yarn add eslint eslint-config-prettier eslint-plugin-prettier eslint-plugin-react
  script:
    - eslint --fix server src
