kind: Deployment
apiVersion: apps/v1
metadata:
  name: <REPOSITORY_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <REPOSITORY_NAME>
  template:
    metadata:
      labels:
        app: <REPOSITORY_NAME>
    spec:
      containers:
        - name: <REPOSITORY_NAME>
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            restartPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10
          ports:
            - containerPort: 3000
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: <REPOSITORY_NAME>
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: <REPOSITORY_NAME>
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: <REPOSITORY_NAME>-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: <REPOSITORY_NAME>.<DOMAIN>
      http:
        paths:
          - backend:
              serviceName: <REPOSITORY_NAME>
              servicePort: 80
