on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Get repository name
        run: echo ::set-env name=REPOSITORY_NAME::astro

      - name: Set tag from git SHA
        run: echo ::set-env name=TAG::$(echo $GITHUB_SHA | head -c7)

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Image
        run: docker build  -t igorsheg/$REPOSITORY_NAME:$TAG .

      - name: Push Image
        run: docker push igorsheg/$REPOSITORY_NAME:$TAG
